# Generated by Django 3.2.5 on 2023-05-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carnumber_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumber',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
