# Generated by Django 3.2.5 on 2023-05-30 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carnumber_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnumber',
            name='date',
        ),
        migrations.AddField(
            model_name='carnumber',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carnumber',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
